branches:
  - main

tagFormat: ${version}

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: docs
          release: patch
        - type: refactor
          release: patch
        - type: style
          release: patch
        - type: ci
          release: patch
        - type: build
          release: patch
        - type: chore
          release: patch
        - type: test
          release: patch

  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: "Features"
            hidden: false
          - type: fix
            section: "Bug Fixes"
            hidden: false
          - type: perf
            section: "Performance"
            hidden: false
          - type: docs
            section: "Documentation"
            hidden: false
          - type: refactor
            section: "Refactoring"
            hidden: false
          - type: style
            section: "Style"
            hidden: false
          - type: ci
            section: "CI/CD"
            hidden: false
          - type: build
            section: "Build"
            hidden: false
          - type: chore
            section: "Chores"
            hidden: false
          - type: test
            section: "Tests"
            hidden: false

  - - "@semantic-release/exec"
    - prepareCmd: "sed -i 's/^version = .*$/version = \"${nextRelease.version}\"/' pyproject.toml && uv lock"

  - - "@semantic-release/github"
    - releaseNameTemplate: "Version ${nextRelease.version}"

  - - "@semantic-release/git"
    - assets:
        - pyproject.toml
        - uv.lock
      message: "chore(release mloda-plugin-template): ${nextRelease.version}"

repositoryUrl: "https://github.com/mloda-ai/mloda-plugin-template"
